name: Sync Fork & Build Docker

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 * * * *'  # every hour
  workflow_dispatch:

jobs:
  sync:
    name: Sync Fork
    runs-on: ubuntu-latest
    outputs:
      updated: ${{ steps.check_updates.outputs.updated }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Add upstream
        run: git remote add upstream https://github.com/sirjmann92/mousetrap.git

      - name: Fetch upstream
        run: git fetch upstream

      - name: Check for updates
        id: check_updates
        run: |
          if [ -z "$(git log HEAD..upstream/main --oneline)" ]; then
            echo "No updates found."
            echo "updated=false" >> $GITHUB_OUTPUT
          else
            echo "Updates found."
            echo "updated=true" >> $GITHUB_OUTPUT
          fi

      - name: Merge upstream/main (excluding workflow file)
        if: steps.check_updates.outputs.updated == 'true'
        run: |
          git checkout main
          git merge upstream/main --no-commit --no-ff
          git restore --source=HEAD --staged --worktree .github/workflows/docker-publish.yml
          git commit -m "Sync from upstream (excluding workflow file)"

      - name: Push changes
        if: steps.check_updates.outputs.updated == 'true'
        run: |
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/johnlucajf/mousetrap.git main

  docker:
    name: Build & Push Docker
    needs: sync
    if: needs.sync.outputs.updated == 'true'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [linux/arm64]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: johnlucajf/mousetrap:latest
          platforms: linux/arm64
