name: Sync Fork & Build Docker

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 * * * *'  # every hour
  workflow_dispatch:      # allows manual trigger

jobs:
  sync:
    name: Sync Fork
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Add upstream
        run: git remote add upstream https://github.com/sirjmann92/mousetrap.git

      - name: Fetch upstream
        run: git fetch upstream

      - name: Merge upstream/main
        run: |
          git checkout main
          git merge upstream/main -m "Sync from upstream"

      - name: Push changes
        run: git push origin main

  docker:
    name: Build & Push Docker
    needs: sync
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [linux/arm64]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: johnlucajf/mousetrap:latest
          platforms: linux/arm64
